// -----------------------------------------------------------------------
// <copyright file="Blocks.cs" company="AillieoTech">
// Copyright (c) AillieoTech. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

// NOTICE: THIS FILE HAS BEEN MODIFIED BY AillieoTech UNDER COMPLIANCE WITH THE APACHE 2.0 LICENCE FROM THE ORIGINAL WORK.
// THE FOLLOWING IS THE COPYRIGHT OF THE ORIGINAL DOCUMENT:

/*
 * Blocks.cs
 * RVO2 Library C#
 *
 * SPDX-FileCopyrightText: 2008 University of North Carolina at Chapel Hill
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please send all bug reports to <geom@cs.unc.edu>.
 *
 * The authors may be contacted via:
 *
 * Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
 * Dept. of Computer Science
 * 201 S. Columbia St.
 * Frederick P. Brooks, Jr. Computer Science Bldg.
 * Chapel Hill, N.C. 27599-3175
 * United States of America
 *
 * <http://gamma.cs.unc.edu/RVO2/>
 */

/*
 * Example file showing a demo with 100 agents split in four groups initially
 * positioned in four corners of the environment. Each agent attempts to move to
 * other side of the environment through a narrow passage generated by four
 * obstacles. There is no roadmap to guide the agents around the obstacles.
 */

namespace RVO
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Unity.Mathematics;
    using UnityEngine;
    using Random = System.Random;

    internal class Blocks : MonoBehaviour
    {
        /* Store the goals of the agents. */
        private IList<float2> goals;

        /** Random number generator. */
        private Random random;

        private void Start()
        {
            this.random = new Random(0);

            this.StartCoroutine(this.Main());
        }

        private void setupScenario()
        {
            this.goals = new List<float2>();

            /* Specify the global time step of the simulation. */
            Simulator.Instance.setTimeStep(0.25f);

            /*
             * Specify the default parameters for agents that are subsequently
             * added.
             */
            Simulator.Instance.setAgentDefaults(15.0f, 10, 5.0f, 5.0f, 2.0f, 2.0f, new float2(0.0f, 0.0f));

            /*
             * Add agents, specifying their start position, and store their
             * goals on the opposite side of the environment.
             */
            for (int i = 0; i < 5; ++i)
            {
                for (int j = 0; j < 5; ++j)
                {
                    Simulator.Instance.addAgent(new float2(55.0f + (i * 10.0f), 55.0f + (j * 10.0f)));
                    this.goals.Add(new float2(-75.0f, -75.0f));

                    Simulator.Instance.addAgent(new float2(-55.0f - (i * 10.0f), 55.0f + (j * 10.0f)));
                    this.goals.Add(new float2(75.0f, -75.0f));

                    Simulator.Instance.addAgent(new float2(55.0f + (i * 10.0f), -55.0f - (j * 10.0f)));
                    this.goals.Add(new float2(-75.0f, 75.0f));

                    Simulator.Instance.addAgent(new float2(-55.0f - (i * 10.0f), -55.0f - (j * 10.0f)));
                    this.goals.Add(new float2(75.0f, 75.0f));
                }
            }

            /*
             * Add (polygonal) obstacles, specifying their vertices in
             * counterclockwise order.
             */
            IList<float2> obstacle1 = new List<float2>
            {
                new float2(-10.0f, 40.0f),
                new float2(-40.0f, 40.0f),
                new float2(-40.0f, 10.0f),
                new float2(-10.0f, 10.0f),
            };
            Simulator.Instance.addObstacle(obstacle1);

            IList<float2> obstacle2 = new List<float2>
            {
                new float2(10.0f, 40.0f),
                new float2(10.0f, 10.0f),
                new float2(40.0f, 10.0f),
                new float2(40.0f, 40.0f),
            };
            Simulator.Instance.addObstacle(obstacle2);

            IList<float2> obstacle3 = new List<float2>
            {
                new float2(10.0f, -40.0f),
                new float2(40.0f, -40.0f),
                new float2(40.0f, -10.0f),
                new float2(10.0f, -10.0f),
            };
            Simulator.Instance.addObstacle(obstacle3);

            IList<float2> obstacle4 = new List<float2>
            {
                new float2(-10.0f, -40.0f),
                new float2(-10.0f, -10.0f),
                new float2(-40.0f, -10.0f),
                new float2(-40.0f, -40.0f),
            };
            Simulator.Instance.addObstacle(obstacle4);

            /*
             * Process the obstacles so that they are accounted for in the
             * simulation.
             */
            Simulator.Instance.processObstacles();
        }

        private void updateVisualization()
        {
            /* Output the current global time. */
            Debug.Log(Simulator.Instance.getGlobalTime());

            /* Output the current position of all the agents. */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                float2 position = Simulator.Instance.getAgentPosition(i);
                Debug.Log($" {position}");
            }

            Debug.Log("\n");
        }

        private void OnDrawGizmos()
        {
            for (int i = 0; i < Simulator.Instance.getNumObstacleVertices(); ++i)
            {
                float2 o = Simulator.Instance.getObstacleVertex(i);
                Gizmos.DrawSphere((Vector2)o, 1);

                int last = i;

                while (true)
                {
                    int next = Simulator.Instance.getNextObstacleVertexNo(last);

                    float2 p0 = Simulator.Instance.getObstacleVertex(last);
                    float2 p1 = Simulator.Instance.getObstacleVertex(next);

                    Gizmos.DrawLine((Vector2)p0, (Vector2)p1);

                    if (next == i)
                    {
                        break;
                    }

                    last = next;
                }

                i = last;
            }

            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                float2 position = Simulator.Instance.getAgentPosition(i);
                Gizmos.DrawSphere((Vector2)position, 1);
            }
        }

        private void setPreferredVelocities()
        {
            /*
             * Set the preferred velocity to be a vector of unit magnitude
             * (speed) in the direction of the goal.
             */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                float2 goalVector = this.goals[i] - Simulator.Instance.getAgentPosition(i);

                if (math.lengthsq(goalVector) > 1.0f)
                {
                    goalVector = math.normalize(goalVector);
                }

                Simulator.Instance.setAgentPrefVelocity(i, goalVector);

                /* Perturb a little to avoid deadlocks due to perfect symmetry. */
                float angle = (float)this.random.NextDouble() * 2.0f * (float)Math.PI;
                float dist = (float)this.random.NextDouble() * 0.0001f;

                Simulator.Instance.setAgentPrefVelocity(
                    i,
                    Simulator.Instance.getAgentPrefVelocity(i) + (dist * new float2((float)Math.Cos(angle), (float)Math.Sin(angle))));
            }
        }

        private bool reachedGoal()
        {
            /* Check if all agents have reached their goals. */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                if (math.lengthsq(Simulator.Instance.getAgentPosition(i) - this.goals[i]) > 400.0f)
                {
                    return false;
                }
            }

            return true;
        }

        private IEnumerator Main()
        {
            do
            {
                /* Set up the scenario. */
                this.setupScenario();

                /* Perform (and manipulate) the simulation. */
                do
                {
                    // updateVisualization();

                    this.setPreferredVelocities();
                    Simulator.Instance.doStep();

                    yield return null;
                }
                while (!this.reachedGoal());

                yield return new WaitForSeconds(1);

                Simulator.Instance.Clear();
            }
            while (true);
        }

        private void OnDestroy()
        {
            Simulator.Instance.Clear();
        }
    }
}
